### ISSUE TITLE
Creating many annotations

### ISSUE THREAD

**Issue by ghost** [anno4j/anno4j#131]
Hi everyone,
I'm facing performance issues when i'm trying to parse the annotations i have stored in a MySQL database to anno4j format. After 8K of annotations stored in memory the throughput of new annotations is 1 at each 3 seconds. Is it normal?

**Comment by berndl** [comment]
Hi @silviodc ,

Two things that come to my mind after reading your issue:

Are you using an Anno4j instance with a local memorystore or the ObjectParser class (which also uses a local memorystore by itself)?
Because then yes, I think that performance issues might happen. Can you try and break up the import into bulks rather than doing all at once?

Are you using namespaces for your annotations? We have experienced heavy performance issues in the past, if you try to use different namespaces that are interwoven with the default graph.

I am currently testing performances with bigger chunks of data, but I am not that far yet :) I will report anything I find back to you if the issue still exists.

**Comment by fischmat** [comment]
Hi @silviodc,

I tried to reconstruct your issue parsing annotations created on the fly with `ObjectParser`.
Unfortunately this drop in throughput seems normal. Here are my timings:

![](http://matthias-fisch.de/images/timings.png)

**Comment by fischmat** [comment]
Hi @silviodc,

the issue can be solved by clearing the triplestore of the `ObjectParser`s underlying Anno4j instance.
Doing so the time needed for parsing an annotation stays low.
![](http://matthias-fisch.de/images/timings_clearing.png) 

But - depending on how @berndl will add this to `ObjectParser` - the `parse()` method will from now on only return the annotation objects extracted during the last call. I hope thats not a problem in your implementation.

Bests,

Matthias

**Comment by berndl** [comment]
Hi @silviodc !
As @fischmat pointed out, we changed the ObjectParser a little bit. The parse method will now clear the ObjectParser's local triplestore after each call. The parsed Annotations are returned by the method.
So if you import your Annotations in bulks, the runtime should stay constantly low.

I pushed the changes to the develop branch, the new SNAPSHOT version should be ready soon!

**Comment by ghost** [comment]
Hi everyone, 
Thanks so much for the support. Right now the import of annotations is working constantly!

**Comment by berndl** [comment]
I think we can close this for now :) Please reopen, if other issues arise!
