### ISSUE TITLE
delete unnecessary alibaba tests

### ISSUE THREAD

**Issue by schlegel** [anno4j/anno4j#56]
testing duration is very long. i think we can remove many tests of the alibaba test suite because we only use a subpart of the hole project and we test it in our project anyways

**Comment by AEisenkolb** [comment]
I reviewed the tests implemented by alibaba. It seams that only a few tests can be deleted without having problems later on. Anyhow, this tests are located in the blob-store and the object-composition and for me, the do not seem very time consuming. I would rather not remove any test from the repository-object, because I think that most of them are useful and helped us very often locating issues produced by anno4j.
